### ISSUE TITLE
Очепятка б.19

### ISSUE THREAD

**Issue by Kre4** [sashafromlibertalia/itmo-db-course#5]
Билет 19
> Отношение находится в нормальной форме Бойса-Кодда, если **детерминанты (зависимые части)** всех зависимостей являются потенциальными ключами.
* X -> Y - в такой зависимости говорят, что X - детерминант, а Y - зависимая часть, значит детерминант не может быть зависимой частью)

**Comment by sashafromlibertalia** [comment]
жду пр :)
